environment:
    matrix:
        - nodejs_version: 8
        - nodejs_version: 9
        - nodejs_version: 10
        - nodejs_version: 11
        - nodejs_version: 12
version: "{build}"
build: off
install:
    - ps: Install-Product node $env:nodejs_version
    - npm install
test_script:
    - node --version
    - npm --version
    - npm test
